spin_manifest_version = 2

[application]
name = "sqs-sample"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
version = "0.1.0"

[[trigger.sqs]]
component = "localtest"
queue_url = "http://localhost:9324/000000000000/test-queue"
max_messages = 1
idle_wait_seconds = 3
system_attributes = ["All"]
message_attributes = ["glonk"]

[component.localtest]
source = "target/wasm32-wasip2/release/guest.wasm"
[component.localtest.build]
command = "cargo build --target wasm32-wasip2 --release"
